### ISSUE TITLE
Support multiple viewports?

### ISSUE THREAD

**Issue by ericchenak** [Quramy/zisui#12]
I like this lib so much.
The API is so simple and so good.
And it's support storybook 5.

However, I cant find a way to run multiple viewports for the storybook.

for example I can do this in `storybook-chrome-screenshot`
```
  withScreenshot({
     viewport: [
      // Mobile
      {
        width: 320,
        height: 568,
        isMobile: true,
        hasTouch: true,
      },
      // Desktop
      {
        width: 1440,
        height: 900,
      },
    ],
  }),
```

It's would be nice that zisui support to run multiple viewports for stories.

**Comment by Quramy** [comment]
@ericchenak Sorry for my late reply. You can use https://github.com/reg-viz/storycap , which is a new version of zisui and supports multiple viewports feature.
