### ISSUE TITLE
exclude.some instead of exclude.every

### ISSUE THREAD

**Issue by nicbillen** [Quramy/zisui#13]
At the moment all items in the exclude array have to match to exclude one story. That is not the expected behaviour. Is it possible to replace exclude.every with exclude.some in util/index.ts, line 24?

Now:
`const excluded = exclude.length ? included.filter(s => !exclude.every(rule => minimatch(s.name, rule))) : included;`

Afterwards:
`const excluded = exclude.length ? included.filter(s => !exclude.some(rule => minimatch(s.name, rule))) : included;`

**Comment by Quramy** [comment]
Thanks, I've merged #14 and published v1.3.2 🎉
